# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: git://github.com/dnephin/pre-commit-golang
  sha: HEAD
  hooks:
  - id: go-fmt
#  - id: go-vet
#  - id: go-lint
  - id: go-build
