version: '3'
services:
  vida-server:
    build: .
#  vida-client:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: vida
      POSTGRES_USER: vida
      POSTGRES_PASSWORD: vida
    volumes:
      - ./pgdata:/var/lib/postgresql/data


# jaeger, prometheus, grfana, kafaka(maybe)