version: '3.7'

services:
  envoy-proxy:
    image: envoyproxy/envoy:latest
    ports:
      - 9090:9090
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    links:
      - vida-grpc
    networks:
      - vida
    command: "/usr/local/bin/envoy -c /etc/envoy/envoy.yaml -l trace --log-path /tmp/envoy_info.log"

  vida-grpc:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: vida
      DB_PASSWORD: vida
      DB_DATABASE: vida
    expose:
      - 50005
    ports:
      - 50005:50005
    links:
      - postgres
    networks:
      - vida
    command: make server-grpc
#  vida-client:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: vida
      POSTGRES_USER: vida
      POSTGRES_PASSWORD: vida
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - vida

  # tracing
  jaeger:
    image: jaegertracing/all-in-one:1.11
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - vida

  # logging with graylog
  mongodb:
    image: mongo:3
    networks:
      - vida

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - vida

  graylog:
    image: graylog/graylog:3.0
    environment:
      # Username: admin, Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - vida

networks:
  vida:

# jaeger, prometheus, grfana, kafaka(maybe)